package br.com.carvalho.podcast.core.designsystem

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Roles from docs/adr/0001-identidade-visual.md, built from [Palette]. Every role is set so none falls back to the
// Material 3 baseline purple; ColorContrastTest checks the usage pairs against WCAG AA.

internal val LightColorScheme = lightColorScheme(
    primary = Color(Palette.AMBER_50),
    onPrimary = Color(Palette.NEUTRAL_10),
    primaryContainer = Color(Palette.AMBER_90),
    onPrimaryContainer = Color(Palette.AMBER_20),
    inversePrimary = Color(Palette.AMBER_70),
    secondary = Color(Palette.SEPIA_40),
    onSecondary = Color(Palette.WHITE),
    secondaryContainer = Color(Palette.SEPIA_90),
    onSecondaryContainer = Color(Palette.SEPIA_10),
    tertiary = Color(Palette.SLATE_40),
    onTertiary = Color(Palette.WHITE),
    tertiaryContainer = Color(Palette.SLATE_90),
    onTertiaryContainer = Color(Palette.SLATE_15),
    background = Color(Palette.NEUTRAL_97),
    onBackground = Color(Palette.NEUTRAL_10),
    surface = Color(Palette.NEUTRAL_97),
    onSurface = Color(Palette.NEUTRAL_10),
    surfaceVariant = Color(Palette.NEUTRAL_88),
    onSurfaceVariant = Color(Palette.NEUTRAL_40),
    surfaceTint = Color(Palette.AMBER_50),
    inverseSurface = Color(Palette.NEUTRAL_20),
    inverseOnSurface = Color(Palette.NEUTRAL_96),
    error = Color(Palette.RED_40),
    onError = Color(Palette.WHITE),
    errorContainer = Color(Palette.RED_90),
    onErrorContainer = Color(Palette.RED_10),
    outline = Color(Palette.NEUTRAL_55),
    outlineVariant = Color(Palette.NEUTRAL_84),
    scrim = Color(Palette.BLACK),
    surfaceBright = Color(Palette.NEUTRAL_97),
    surfaceContainer = Color(Palette.NEUTRAL_92),
    surfaceContainerHigh = Color(Palette.NEUTRAL_90),
    surfaceContainerHighest = Color(Palette.NEUTRAL_88),
    surfaceContainerLow = Color(Palette.NEUTRAL_95),
    surfaceContainerLowest = Color(Palette.WHITE),
    surfaceDim = Color(Palette.NEUTRAL_86),
    primaryFixed = Color(Palette.AMBER_90),
    primaryFixedDim = Color(Palette.AMBER_70),
    onPrimaryFixed = Color(Palette.AMBER_10),
    onPrimaryFixedVariant = Color(Palette.AMBER_25),
    secondaryFixed = Color(Palette.SEPIA_90),
    secondaryFixedDim = Color(Palette.SEPIA_80),
    onSecondaryFixed = Color(Palette.SEPIA_10),
    onSecondaryFixedVariant = Color(Palette.SEPIA_30),
    tertiaryFixed = Color(Palette.SLATE_90),
    tertiaryFixedDim = Color(Palette.SLATE_80),
    onTertiaryFixed = Color(Palette.SLATE_15),
    onTertiaryFixedVariant = Color(Palette.SLATE_30),
)

internal val DarkColorScheme = darkColorScheme(
    primary = Color(Palette.AMBER_70),
    onPrimary = Color(Palette.NEUTRAL_10),
    primaryContainer = Color(Palette.AMBER_25),
    onPrimaryContainer = Color(Palette.AMBER_90),
    inversePrimary = Color(Palette.AMBER_40),
    secondary = Color(Palette.SEPIA_80),
    onSecondary = Color(Palette.SEPIA_10),
    secondaryContainer = Color(Palette.SEPIA_30),
    onSecondaryContainer = Color(Palette.SEPIA_90),
    tertiary = Color(Palette.SLATE_80),
    onTertiary = Color(Palette.SLATE_15),
    tertiaryContainer = Color(Palette.SLATE_30),
    onTertiaryContainer = Color(Palette.SLATE_90),
    background = Color(Palette.NEUTRAL_6),
    onBackground = Color(Palette.NEUTRAL_94),
    surface = Color(Palette.NEUTRAL_6),
    onSurface = Color(Palette.NEUTRAL_94),
    surfaceVariant = Color(Palette.NEUTRAL_22),
    onSurfaceVariant = Color(Palette.NEUTRAL_66),
    surfaceTint = Color(Palette.AMBER_70),
    inverseSurface = Color(Palette.NEUTRAL_94),
    inverseOnSurface = Color(Palette.NEUTRAL_20),
    error = Color(Palette.RED_80),
    onError = Color(Palette.RED_20),
    errorContainer = Color(Palette.RED_30),
    onErrorContainer = Color(Palette.RED_92),
    outline = Color(Palette.NEUTRAL_50),
    outlineVariant = Color(Palette.NEUTRAL_24),
    scrim = Color(Palette.BLACK),
    surfaceBright = Color(Palette.NEUTRAL_25),
    surfaceContainer = Color(Palette.NEUTRAL_12),
    surfaceContainerHigh = Color(Palette.NEUTRAL_17),
    surfaceContainerHighest = Color(Palette.NEUTRAL_22),
    surfaceContainerLow = Color(Palette.NEUTRAL_11),
    surfaceContainerLowest = Color(Palette.NEUTRAL_4),
    surfaceDim = Color(Palette.NEUTRAL_6),
    primaryFixed = Color(Palette.AMBER_90),
    primaryFixedDim = Color(Palette.AMBER_70),
    onPrimaryFixed = Color(Palette.AMBER_10),
    onPrimaryFixedVariant = Color(Palette.AMBER_25),
    secondaryFixed = Color(Palette.SEPIA_90),
    secondaryFixedDim = Color(Palette.SEPIA_80),
    onSecondaryFixed = Color(Palette.SEPIA_10),
    onSecondaryFixedVariant = Color(Palette.SEPIA_30),
    tertiaryFixed = Color(Palette.SLATE_90),
    tertiaryFixedDim = Color(Palette.SLATE_80),
    onTertiaryFixed = Color(Palette.SLATE_15),
    onTertiaryFixedVariant = Color(Palette.SLATE_30),
)
