plugins {
    alias(libs.plugins.podcast.kmp.library)
    alias(libs.plugins.kotlin.serialization)
}

kotlin {
    android {
        namespace = "br.com.carvalho.podcast.data"
        withHostTest {}
    }

    sourceSets {
        commonMain.dependencies {
            api(project(":domain"))
            implementation(project(":core:common"))
            implementation(project(":core:database"))
            implementation(project(":core:network"))
            implementation(project(":core:observability"))
            implementation(libs.ktor.client.core)
            implementation(libs.kotlinx.serialization)
            implementation(libs.kotlinx.datetime)
            implementation(libs.paging.common)
            implementation(libs.okio)
        }
        commonTest.dependencies {
            implementation(project(":core:testing"))
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
            implementation(libs.turbine)
            implementation(libs.ktor.client.mock)
            implementation(libs.okio.fakefilesystem)
            implementation(libs.paging.testing)
        }
    }
}

// Real feeds for the parser tests (15.2). Wasm tests cannot read files, so each XML becomes a string in generated
// common test code: `FeedFixtures.all["hipsters"]`.
val feedFixturesDir = layout.projectDirectory.dir("src/commonTest/resources/feeds")
val generateFeedFixtures by tasks.registering {
    val input = feedFixturesDir
    val output = layout.buildDirectory.dir("generated/feedFixtures/kotlin")
    inputs.dir(input)
    outputs.dir(output)
    doLast {
        // JVM string constants are capped at 64 KB, so each file is split into chunks.
        val chunkSize = 8_000
        val entries = input.asFile.listFiles { file -> file.extension == "xml" }.orEmpty().sortedBy { it.name }
            .joinToString("\n") { file ->
                val chunks = file.readText().chunked(chunkSize).joinToString(",\n") { chunk ->
                    val escaped = chunk.replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$")
                        .replace("\r", "\\r").replace("\n", "\\n")
                    "            \"$escaped\""
                }
                "        \"${file.nameWithoutExtension}\" to listOf(\n$chunks,\n        ).joinToString(\"\"),"
            }
        val target = output.get().file("br/com/carvalho/podcast/data/remote/FeedFixtures.kt").asFile
        target.parentFile.mkdirs()
        target.writeText(
            "package br.com.carvalho.podcast.data.remote\n\n" +
                "// Generated by :data:generateFeedFixtures from src/commonTest/resources/feeds. Do not edit.\n" +
                "object FeedFixtures {\n    val all: Map<String, String> = mapOf(\n$entries\n    )\n}\n"
        )
    }
}
kotlin.sourceSets.commonTest {
    kotlin.srcDir(generateFeedFixtures)
}
