name: 'gradle-setup'
description: 'Setup Java and Gradle'
runs:
    using: "composite"
    steps:
        -   name: Setup Java
            uses: actions/setup-java@v4
            with:
                java-version: "21"
                distribution: "temurin"

        -   name: Setup Gradle
            uses: gradle/actions/setup-gradle@v4

        -   name: Cache CocoaPods
            uses: actions/cache@v4
            with:
                path: |
                    ~/.cocoapods
                    shared/build/cocoapods
                    Pods
                    shared/build/cocoapods/synthetic
                key: ${{ runner.os }}-cocoapods-v2-${{ hashFiles('shared/build.gradle.kts', '**/Podfile.lock') }}
                restore-keys: |
                    ${{ runner.os }}-cocoapods-v2-
